version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./Table.sql:/docker-entrypoint-initdb.d/Table.sql
      - ./Function.sql:/docker-entrypoint-initdb.d/Function.sql
    environment:
      POSTGRES_DB: "ForkLog"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"

  myapp:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres


