CREATE TABLE IF NOT EXISTS public."Visited"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    url text COLLATE pg_catalog."default",
    CONSTRAINT "Visited_pkey" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Visited"
    OWNER to postgres;